apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::939115191277:user/francyalinston
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::939115191277:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OUI279WNXORM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-31T20:14:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "880"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 36423580-4825-11ea-a473-060a435a9e52